import os
from pathlib import Path


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value.strip())
    except ValueError:
        return default


TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "").strip()

STATE_FILE = Path(os.getenv("STATE_FILE", "state.json"))
DATABASE_PATH = Path(os.getenv("DATABASE_PATH", "bot_state.db"))
HOSTING_MODE = _env_bool("HOSTING_MODE", False)
BYBIT_BASE_URL = os.getenv("BYBIT_BASE_URL", "https://api.bybit.com").strip()

OI_THRESHOLD_PERCENT = 4
PRICE_CHANGE_THRESHOLD_PERCENT = 1
VOLUME_SPIKE_MULTIPLIER = 2
ALERT_COOLDOWN_MINUTES = 30
SCAN_INTERVAL_SECONDS = _env_int("SCAN_INTERVAL_SECONDS", 60)
HISTORY_WINDOW_MINUTES = 30
MIN_24H_TURNOVER_USDT = 5_000_000
MAX_SYMBOLS_TO_MONITOR = 300
EXCLUDED_SYMBOL_KEYWORDS = [
    "1000",
    "10000",
]

RSI_PERIOD = 14
EMA_FAST_PERIOD = 20
EMA_SLOW_PERIOD = 50
MACD_FAST_PERIOD = 12
MACD_SLOW_PERIOD = 26
MACD_SIGNAL_PERIOD = 9
ATR_PERIOD = 14
KLINE_INTERVAL = "1"
KLINE_LIMIT = 100
ENABLE_INDICATORS = True
ENABLE_SETUP_GENERATOR = True
SETUP_ATR_ENTRY_MULTIPLIER = 0.35
SETUP_ATR_STOP_MULTIPLIER = 1.2
SETUP_TP1_R_MULTIPLIER = 1.5
SETUP_TP2_R_MULTIPLIER = 2.5
MIN_RISK_REWARD = 1.5
MIN_PULLBACK_PERCENT_NORMAL = 0.5
MIN_PULLBACK_PERCENT_HIGH_RISK = 0.8
MIN_PULLBACK_PERCENT_EXTREME_RISK = 1.2
MAX_ENTRY_CHASE_DISTANCE_PERCENT = 0.35
OVERBOUGHT_RSI_LEVEL = 70
EXTREME_OVERBOUGHT_RSI_LEVEL = 80
OVERSOLD_RSI_LEVEL = 30
EXTREME_OVERSOLD_RSI_LEVEL = 20
HIGH_VOLUME_SPIKE_LEVEL = 10
EXTREME_VOLUME_SPIKE_LEVEL = 20
SETUP_MIN_PRICE_CHANGE_PERCENT = 0.8
SETUP_MIN_OI_CHANGE_PERCENT = 2.0
SETUP_MIN_VOLUME_SPIKE = 1.5
SETUP_MIN_ATR_PERCENT = 0.15
SETUP_CLEAN_MIN_PRICE_CHANGE_PERCENT = 1.0
SETUP_CLEAN_MIN_OI_CHANGE_PERCENT = 3.0
SETUP_CLEAN_MIN_VOLUME_SPIKE = 1.8
SETUP_ALLOW_WEAK_SQUEEZE = True
ENABLE_SETUP_TRACKING = True
SETUP_TRACKING_EXPIRATION_HOURS = 6
SETUP_TRACKING_MAX_ACTIVE = 50
SETUP_TRACKING_CHECK_INTERVAL_SECONDS = 60
SETUP_TOUCH_MODE = "wick"
SETUP_JOURNAL_MAX_RECORDS = 500

LOOKBACK_MINUTES = 15
SYMBOL_REFRESH_INTERVAL_MINUTES = 30
MAX_ALERTS_PER_SCAN = 10
RECENT_ALERTS_LIMIT = 50

REQUEST_TIMEOUT_SECONDS = 10
MAX_RETRIES = 3
RETRY_BACKOFF_SECONDS = 2
TELEGRAM_POLL_TIMEOUT_SECONDS = 2
TELEGRAM_MIN_SECONDS_BETWEEN_MESSAGES = 1.0


def validate_config() -> None:
    missing = []
    if not TELEGRAM_BOT_TOKEN:
        missing.append("TELEGRAM_BOT_TOKEN")
    if not TELEGRAM_CHAT_ID:
        missing.append("TELEGRAM_CHAT_ID")

    if missing:
        names = ", ".join(missing)
        raise RuntimeError(f"Missing required environment variables: {names}")
