import os
from pathlib import Path


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value.strip())
    except ValueError:
        return default


def _env_float(name: str, default: float) -> float:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return float(value.strip())
    except ValueError:
        return default


def _env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip().upper() for item in value.split(",") if item.strip()]


TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "").strip()

STATE_FILE = Path(os.getenv("STATE_FILE", "state.json"))
DATABASE_PATH = Path(os.getenv("DATABASE_PATH", "bot_state.db"))
HOSTING_MODE = _env_bool("HOSTING_MODE", False)
BYBIT_BASE_URL = os.getenv("BYBIT_BASE_URL", "https://api.bybit.com").strip()

BYBIT_API_KEY = os.getenv("BYBIT_API_KEY", "").strip()
BYBIT_API_SECRET = os.getenv("BYBIT_API_SECRET", "").strip()
BYBIT_TESTNET = _env_bool("BYBIT_TESTNET", True)
BYBIT_TRADING_ENABLED = _env_bool("BYBIT_TRADING_ENABLED", False)

OI_THRESHOLD_PERCENT = 4
PRICE_CHANGE_THRESHOLD_PERCENT = 1
VOLUME_SPIKE_MULTIPLIER = 2
ALERT_COOLDOWN_MINUTES = 30
SCAN_INTERVAL_SECONDS = _env_int("SCAN_INTERVAL_SECONDS", 60)
HISTORY_WINDOW_MINUTES = 30
MIN_24H_TURNOVER_USDT = 5_000_000
MAX_SYMBOLS_TO_MONITOR = 300
EXCLUDED_SYMBOL_KEYWORDS = [
    "1000",
    "10000",
]

RSI_PERIOD = 14
EMA_FAST_PERIOD = 20
EMA_SLOW_PERIOD = 50
MACD_FAST_PERIOD = 12
MACD_SLOW_PERIOD = 26
MACD_SIGNAL_PERIOD = 9
ATR_PERIOD = 14
KLINE_INTERVAL = "1"
KLINE_LIMIT = 100
ENABLE_INDICATORS = True
ENABLE_SETUP_GENERATOR = True
SETUP_ATR_ENTRY_MULTIPLIER = 0.35
SETUP_ATR_STOP_MULTIPLIER = 1.2
SETUP_TP1_R_MULTIPLIER = 1.5
SETUP_TP2_R_MULTIPLIER = 2.5
MIN_RISK_REWARD = 1.5
MIN_PULLBACK_PERCENT_NORMAL = 0.5
MIN_PULLBACK_PERCENT_HIGH_RISK = 0.8
MIN_PULLBACK_PERCENT_EXTREME_RISK = 1.2
MAX_ENTRY_CHASE_DISTANCE_PERCENT = 0.35
MAX_CHASE_DISTANCE_PERCENT = MAX_ENTRY_CHASE_DISTANCE_PERCENT
OVERBOUGHT_RSI_LEVEL = 70
EXTREME_OVERBOUGHT_RSI_LEVEL = 80
OVERSOLD_RSI_LEVEL = 30
EXTREME_OVERSOLD_RSI_LEVEL = 20
HIGH_VOLUME_SPIKE_LEVEL = 10
EXTREME_VOLUME_SPIKE_LEVEL = 20
SETUP_MIN_PRICE_CHANGE_PERCENT = 0.8
SETUP_MIN_OI_CHANGE_PERCENT = 2.0
SETUP_MIN_VOLUME_SPIKE = 1.5
SETUP_MIN_ATR_PERCENT = 0.15
SETUP_CLEAN_MIN_PRICE_CHANGE_PERCENT = 1.0
SETUP_CLEAN_MIN_OI_CHANGE_PERCENT = 3.0
SETUP_CLEAN_MIN_VOLUME_SPIKE = 1.8
SETUP_ALLOW_WEAK_SQUEEZE = True
ENABLE_SETUP_TRACKING = True
SETUP_TRACKING_EXPIRATION_HOURS = 6
SETUP_TRACKING_MAX_ACTIVE = 50
SETUP_TRACKING_CHECK_INTERVAL_SECONDS = 60
SETUP_TOUCH_MODE = "wick"
SETUP_JOURNAL_MAX_RECORDS = 500

DERIVATIVES_TAKER_FEE_PERCENT = _env_float("DERIVATIVES_TAKER_FEE_PERCENT", 0.1000)
DERIVATIVES_MAKER_FEE_PERCENT = _env_float("DERIVATIVES_MAKER_FEE_PERCENT", 0.0360)
SPOT_TAKER_FEE_PERCENT = _env_float("SPOT_TAKER_FEE_PERCENT", 0.1800)
SPOT_MAKER_FEE_PERCENT = _env_float("SPOT_MAKER_FEE_PERCENT", 0.1000)
FEE_MODE = os.getenv("FEE_MODE", "maker").strip().lower() or "maker"
BYBIT_TAKER_FEE_RATE = DERIVATIVES_TAKER_FEE_PERCENT / 100
BYBIT_MAKER_FEE_RATE = DERIVATIVES_MAKER_FEE_PERCENT / 100
DEFAULT_EXECUTION_FEE_MODE = FEE_MODE
SLIPPAGE_PERCENT = 0.03
MIN_SECONDS_AFTER_ALERT_FOR_ENTRY = 10

ACCOUNT_RISK_PERCENT = _env_float("ACCOUNT_RISK_PERCENT", 1.0)
MAX_POSITION_USDT = _env_float("MAX_POSITION_USDT", 50.0)
MIN_POSITION_USDT = _env_float("MIN_POSITION_USDT", 5.0)
MAX_LEVERAGE = _env_int("MAX_LEVERAGE", 5)
DEFAULT_LEVERAGE = _env_int("DEFAULT_LEVERAGE", 3)
MIN_RR_TO_ALLOW_ORDER = _env_float("MIN_RR_TO_ALLOW_ORDER", 1.5)
ALLOW_HIGH_RISK_ORDERS = _env_bool("ALLOW_HIGH_RISK_ORDERS", False)
PAPER_ACCOUNT_BALANCE_USDT = _env_float("PAPER_ACCOUNT_BALANCE_USDT", 100.0)

REAL_MODE_UNLOCK_MIN_CLOSED_SETUPS = _env_int("REAL_MODE_UNLOCK_MIN_CLOSED_SETUPS", 100)
REAL_MODE_UNLOCK_MIN_WIN_RATE = _env_float("REAL_MODE_UNLOCK_MIN_WIN_RATE", 80.0)
REAL_MODE_UNLOCK_MIN_NET_R = _env_float("REAL_MODE_UNLOCK_MIN_NET_R", 10.0)
REAL_MODE_COUNT_FAST_MOVE = _env_bool("REAL_MODE_COUNT_FAST_MOVE", False)
REAL_MODE_REQUIRE_REALISTIC_ONLY = _env_bool("REAL_MODE_REQUIRE_REALISTIC_ONLY", True)
REAL_TRADING_UNLOCKED_DEFAULT = _env_bool("REAL_TRADING_UNLOCKED_DEFAULT", False)
REAL_TRADING_CONFIRMATION_REQUIRED = _env_bool("REAL_TRADING_CONFIRMATION_REQUIRED", True)
REAL_DRY_RUN_ENABLED = _env_bool("REAL_DRY_RUN_ENABLED", True)
MAINNET_READ_ONLY_MODE = _env_bool("MAINNET_READ_ONLY_MODE", True)
TESTNET_AUTOPILOT_ENABLED = _env_bool("TESTNET_AUTOPILOT_ENABLED", False)
TESTNET_AUTOPILOT_REQUIRE_REALISTIC = _env_bool("TESTNET_AUTOPILOT_REQUIRE_REALISTIC", True)
TESTNET_AUTOPILOT_ALLOW_HIGH_RISK = _env_bool("TESTNET_AUTOPILOT_ALLOW_HIGH_RISK", False)
TESTNET_AUTOPILOT_ALLOW_FAST_MOVE = _env_bool("TESTNET_AUTOPILOT_ALLOW_FAST_MOVE", False)
TESTNET_AUTOPILOT_ALLOW_AMBIGUOUS = _env_bool("TESTNET_AUTOPILOT_ALLOW_AMBIGUOUS", False)
TESTNET_AUTOPILOT_MAX_ORDERS_PER_DAY = _env_int("TESTNET_AUTOPILOT_MAX_ORDERS_PER_DAY", 3)
TESTNET_AUTOPILOT_MAX_ACTIVE_ORDERS = _env_int("TESTNET_AUTOPILOT_MAX_ACTIVE_ORDERS", 2)
TESTNET_AUTOPILOT_MIN_RR = _env_float("TESTNET_AUTOPILOT_MIN_RR", 1.5)
TESTNET_AUTOPILOT_ALLOWED_ALERT_TYPES = _env_list(
    "TESTNET_AUTOPILOT_ALLOWED_ALERT_TYPES",
    [
        "Clean Bullish Momentum",
        "Clean Bearish Pressure",
        "Possible Short Squeeze",
        "Possible Long Squeeze",
    ],
)
ORDER_SYNC_ENABLED = _env_bool("ORDER_SYNC_ENABLED", True)
ORDER_SYNC_INTERVAL_SECONDS = _env_int("ORDER_SYNC_INTERVAL_SECONDS", 30)
ORDER_MAX_LIFETIME_MINUTES = _env_int("ORDER_MAX_LIFETIME_MINUTES", 30)
AUTO_CANCEL_EXPIRED_ORDERS = _env_bool("AUTO_CANCEL_EXPIRED_ORDERS", True)
AUTO_CANCEL_INVALIDATED_BEFORE_FILL = _env_bool("AUTO_CANCEL_INVALIDATED_BEFORE_FILL", True)
AUTO_PLACE_TP_SL = _env_bool("AUTO_PLACE_TP_SL", False)

DAILY_REPORT_ENABLED = _env_bool("DAILY_REPORT_ENABLED", True)
DAILY_REPORT_HOUR_UTC = _env_int("DAILY_REPORT_HOUR_UTC", 21)
DAILY_REPORT_CHAT_ID = os.getenv("DAILY_REPORT_CHAT_ID", TELEGRAM_CHAT_ID).strip()
SYMBOL_BLACKLIST = _env_list("SYMBOL_BLACKLIST", [])

BACKTEST_ENABLED = _env_bool("BACKTEST_ENABLED", True)
BACKTEST_DEFAULT_DAYS = _env_int("BACKTEST_DEFAULT_DAYS", 7)
BACKTEST_DEFAULT_INTERVAL = os.getenv("BACKTEST_DEFAULT_INTERVAL", "1m").strip() or "1m"
BACKTEST_MAX_SYMBOLS = _env_int("BACKTEST_MAX_SYMBOLS", 50)
BACKTEST_MIN_24H_TURNOVER = _env_float("BACKTEST_MIN_24H_TURNOVER", 5_000_000)
BACKTEST_MAX_CANDLES_PER_SYMBOL = _env_int("BACKTEST_MAX_CANDLES_PER_SYMBOL", 10_000)

LOOKBACK_MINUTES = 15
SYMBOL_REFRESH_INTERVAL_MINUTES = 30
MAX_ALERTS_PER_SCAN = 10
RECENT_ALERTS_LIMIT = 50

REQUEST_TIMEOUT_SECONDS = 10
MAX_RETRIES = 3
RETRY_BACKOFF_SECONDS = 2
TELEGRAM_POLL_TIMEOUT_SECONDS = 2
TELEGRAM_MIN_SECONDS_BETWEEN_MESSAGES = 1.0


def validate_config() -> None:
    missing = []
    if not TELEGRAM_BOT_TOKEN:
        missing.append("TELEGRAM_BOT_TOKEN")
    if not TELEGRAM_CHAT_ID:
        missing.append("TELEGRAM_CHAT_ID")

    if missing:
        names = ", ".join(missing)
        raise RuntimeError(f"Missing required environment variables: {names}")
